apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-09dd25a32aaa703c0
  capacity:
    storage: 25Gi
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      project: roboshop
      component: frontend
  template:
    metadata:
      labels:
        app: nginx
        project: roboshop
        component: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-html
          mountPath: "/usr/share/nginx/html"
      volumes:
      - name: nginx-html
        persistentVolumeClaim:
          claimName: ebs-static-pvc 