apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels: # these lables are replicaset lables.
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels: # these lables should match with pod labels.
      tier: frontend
      app: nginx
      environment: dev
  template: # the one is nothing but pod definition.
    metadata: # these are the pod lables
      labels:
        tier: frontend
        app: nginx
        environment: dev
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2ss
