apiVersion: v1
kind: Secret
metadata:
  name: secret-base-auth
data:
  username: c2FudGhwcmFrYXNoCg==
  password: YWJjMTIzCg==
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: config-pod-direct
    image: nginx
    envFrom:
    - secretRef:
        name: secret-base-auth
